Repository ultratendency/kafka-ldap-integration, pull requests merged in 2023-10, with the labels that each got.

#366 chore: Add release-please workflow
  .github/release.yml
  .github/workflows/release-please.yml
  build.gradle
Labels: enhancement, size/S

#358 feat!: Add support for Kafka 3.3.2
  .github/workflows/gradle-publish.yml
  .github/workflows/gradle.yml
  .github/workflows/sonarcloud.yml
  Dockerfile
  README.md
  build.gradle
  src/main/kotlin/com/ultratendency/kafka/ldap/authorization/GroupAuthorizer.kt
  src/main/kotlin/com/ultratendency/kafka/ldap/authorization/LDAPAuthorization.kt
  src/main/kotlin/com/ultratendency/kafka/ldap/authorization/SimpleLDAPAuthorizer.kt
  src/test/kotlin/com/ultratendency/kafka/ldap/authorization/GroupAuthorizerSpec.kt
  src/test/kotlin/com/ultratendency/kafka/ldap/authorization/LDAPAuthorizationSpec.kt
Labels: documentation, enhancement, size/XL

#369 chore: Fix typo in README
  README.md
Labels: documentation, size/XS

#370 chore: Add pull_request_target goals to linter & Gradle workflow
  .github/workflows/gradle.yml
  .github/workflows/linter.yml
Labels: enhancement, size/XS

#371 chore: Add workflow to apply conventional labels
  .github/workflows/conventional-labels.yml
Labels: enhancement, size/XS

#372 chore: Update workflow to better handle Dependabot
  .github/workflows/gradle.yml
  .github/workflows/linter.yml
Labels: enhancement, size/XS, ignore-for-release

#373 chore: Release 2.1.0
  build.gradle
Labels: enhancement, size/XS, ignore-for-release

#374 chore: Start version 2.1.1-SNAPSHOT
  build.gradle
Labels: enhancement, size/XS, ignore-for-release

#375 chore: Fix parameter name for release-please-action
  .github/workflows/release-please.yml
Labels: bug, size/XS, ignore-for-release
